package com.ashwini.pub_bzs_cns_all_bre_data_rule_publish;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PR_combined implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer data_ppmonth;
	private java.math.BigDecimal factors;

	public PR_combined() {
	}

	public java.lang.Integer getData_ppmonth() {
		return this.data_ppmonth;
	}

	public void setData_ppmonth(java.lang.Integer data_ppmonth) {
		this.data_ppmonth = data_ppmonth;
	}

	public java.math.BigDecimal getFactors() {
		return this.factors;
	}

	public void setFactors(java.math.BigDecimal factors) {
		this.factors = factors;
	}

	public PR_combined(java.lang.Integer data_ppmonth,
			java.math.BigDecimal factors) {
		this.data_ppmonth = data_ppmonth;
		this.factors = factors;
	}

}