package com.ashwini.pub_bzs_cns_all_bre_data_rule_publish;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class cns_data_file implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	public cns_data_file() {
	}

}